kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: mysc
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
  zones: us-west-1,us-east-1d, us-east-1c
  iopsPerGB: "10"
  fsType: ext4
